---

- name: Create directories in your Shopware folder in the webserver_root path
  file:
    path: "{{ webserver_root }}/shopware/{{ item }}"
    state: directory
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
  become: yes
  with_items:
    - custom/plugins
    - custom/project
    - files/documents
    - files/downloads
    - media/archive
    - media/image/thumbnail
    - media/music
    - media/pdf
    - media/temp
    - media/unknown
    - media/vector
    - media/video
    - themes/Frontend

- name: Remove Shopware Source
  shell: rm -rf {{ webserver_root }}/../shopware

- name: Clone Shopware
  shell: git clone https://github.com/shopware/shopware.git {{ webserver_root }}/../shopware

- name: Update Shopware repository and checkout your desired version.
  command: "{{ item }} chdir={{ webserver_root }}/../shopware"
  with_items:
    - git checkout tags/{{ shopware_version }}

- name: Create symlinks for the Shopware core files in your shopware folder in the webserver_root path
  shell: "yes | ln -sfF {{ webserver_root }}/../shopware/{{ item }} chdir={{ webserver_root }}/shopware"
  become: yes
  with_items:
    - _sql
    - bin
    - build
    - dev-ops
    - engine
    - files/documents/.htaccess
    - media/.htaccess
    - media/temp/.htaccess
    - recovery
    - test
    - themes/Backend
    - themes/Frontend/Bare
    - themes/Frontend/Responsive
    - var
    - vendor
    - web
    - .htaccess
    - autoload.php
    - shopware.php

- name: Set file permissions for Shopware
  command: chmod -R 755 {{ item }} chdir={{ webserver_root }}/shopware
  become: yes
  with_items:
    - var
    - web
    - files
    - media
    - engine/Shopware/Plugins/Community

- name: copy configure.answer file
  template: src=configure.answer dest={{ webserver_root }}/../bin/configure.answer owner=vagrant mode=0775
  become: yes

- name: Build Shopware
  shell: "{{ item }} chdir={{ webserver_root }}/../shopware/build"
  become: yes
  with_items:
#    - "ant configure <<< 'localhost\n3306\nshopware\nshopware\nshopware\n{{ ansible_fqdn }}\n\n'"
    - ~/bin/configure.answer
    - ant build-unit
