---

- name: Create directories in your Shopware folder in the webserver_root path
  file:
    path: "{{ webserver_root }}/shopware/{{ item }}"
    state: directory
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
    force: yes
  become: yes
  with_items:
    - custom/plugins
    - custom/project
    - files/documents
    - files/downloads
    - media/archive
    - media/image/thumbnail
    - media/music
    - media/pdf
    - media/temp
    - media/unknown
    - media/vector
    - media/video
    - themes/Frontend

- name: Remove Shopware Source
  become: yes
  shell: rm -rf {{ webserver_root }}/../shopware

- name: Clone Shopware
  shell: git clone https://github.com/shopware/shopware.git {{ webserver_root }}/../shopware

- name: Update Shopware repository and checkout your desired version.
  command: "{{ item }} chdir={{ webserver_root }}/../shopware"
  with_items:
    - git checkout tags/{{ shopware_version }}

- name: Create symflinks for the Shopware source files and folders
  become: yes
  file:
    src: "/home/vagrant/shopware/{{ item }}"
    dest: "/home/vagrant/www/shopware/{{ item }}"
    state: link
    group: "{{ webserver_group }}"
    owner: "{{ webserver_user }}"
    force: yes
  with_items:
    - _sql
    - bin
    - build
    - dev-ops
    - engine
    - files/documents/.htaccess
    - media/.htaccess
    - media/temp/.htaccess
    - recovery
    - tests
    - themes/Backend
    - themes/Frontend/Bare
    - themes/Frontend/Responsive
    - var
    - vendor
    - web
    - .htaccess
    - autoload.php
    - shopware.php

# - name: Set file permissions for Shopware document root
#   file:
#     path: "{{ webserver_root }}/shopware/{{ item }}"
#     mode: 0775
#     state: directory
#     force: yes
#     recurse: yes
#   become: yes
#   with_items:
#     - var
#     - web
#     - files
#     - media
#     - engine/Shopware/Plugins/Community

- name: Set file permissions for Shopware source
  become: yes
  file:
    path: "{{ webserver_root }}/../shopware/{{ item }}"
    mode: 0775
    state: directory
    force: yes
    recurse: yes
  with_items:
    - var
    - web
    - files
    - media
    - engine/Shopware/Plugins/Community

- name: Copy build.properties file
  when: shopware_install == "demo" || shopware_install == "clean"
  template: src=build.properties dest={{ webserver_root }}/../shopware/build/build.properties owner=vagrant mode=0775
  become: yes

- name: Create shopware db
  when: dbms == "mysql"
  mysql_db: name=shopware state=present
  become: yes

- name: Create shopware db user
  when: dbms == "mysql"
  mysql_user: name={{ shopware_db_username}} password={{ shopware_db_password}} priv={{ shopware_db_name }}.*:ALL state=present
  become: yes

- name: Build Shopware
  when: shopware_install == "demo" || shopware_install == "clean"
  shell: "{{ item }} chdir={{ webserver_root }}/../shopware/build"
  become: yes
  with_items:
    - ant build-unit

- name: Create symflinks for the Shopware source files and folders
  file:
    src: "/home/vagrant/shopware/{{ item }}"
    dest: "/home/vagrant/www/shopware/{{ item }}"
    state: link
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
  with_items:
    - config.php
