---

- name: Check Node version
  command: node -v
  register: nodejs_current
  ignore_errors: true

- name: Check NPM version
  command: npm -v
  register: npm_current
  ignore_errors: true

# First time the role is run, we need to install Node's latest version to include NPM (we might downgrade later if needed)
- name: Install Node (first time)
  include: install_node.yml
  become: yes

- name: Update NPM to specific version
  become: yes
  npm:
    name: npm
    version: "stable"
    state: present
    global: yes

# Update Node version
- name: Clean NPM cache
  become: yes
  command: npm cache clean -f

- name: Check for "n" NPM package
  become: yes
  npm: name=n state=present global=yes

- name: Update Node version
  become: yes
  command: n {{nodejs_version}}

# NPM Packages
- name: Install NPM Packages
  become: yes
  npm:
    name: "{{item}}"
    state: present
    global: yes
  with_items: "{{npm_packages}}"
