---

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - zsh
    - nodejs
    - php
    - mysql
    - apache
    - composer
    - ioncube
    - grunt
    - shopware-cli
    - shopware
    - adminer